/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    MyAutoUpload: typeof import('./src/components/common/Upload/MyAutoUpload/index.vue')['default']
    MyButton: typeof import('./src/components/common/MyButton/index.vue')['default']
    MyDialog: typeof import('./src/components/common/MyDialog/index.vue')['default']
    MyEcharts: typeof import('./src/components/common/MyEcharts/index.vue')['default']
    MyIcon: typeof import('./src/components/common/MyIcon/index.vue')['default']
    MyImageAutoUpload: typeof import('./src/components/common/Upload/MyImageAutoUpload/index.vue')['default']
    MyPagination: typeof import('./src/components/common/MyPagination/index.vue')['default']
    MyTable: typeof import('./src/components/common/MyTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectIcon: typeof import('./src/components/SelectIcon/index.vue')['default']
    SelectImage: typeof import('./src/components/SelectImage/index.vue')['default']
    SysSettings: typeof import('./src/views/components/SysSettings/index.vue')['default']
  }
}
