/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AInputTag: typeof import('@arco-design/web-vue')['InputTag']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AOption: typeof import('@arco-design/web-vue')['Option']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATimePicker: typeof import('@arco-design/web-vue')['TimePicker']
    MyButton: typeof import('./src/components/MyButton/index.vue')['default']
    MyDialog: typeof import('./src/components/MyDialog/index.vue')['default']
    MyEcharts: typeof import('./src/components/MyEcharts/index.vue')['default']
    MyIcon: typeof import('./src/components/MyIcon/index.vue')['default']
    MyPagination: typeof import('./src/components/MyPagination/index.vue')['default']
    MyTable: typeof import('./src/components/MyTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysSettings: typeof import('./src/views/components/SysSettings/index.vue')['default']
  }
}
