/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    MyDialog: typeof import('./src/components/MyDialog/index.vue')['default']
    MyEcharts: typeof import('./src/components/MyEcharts/index.vue')['default']
    MyPagination: typeof import('./src/components/MyPagination/index.vue')['default']
    MyTable: typeof import('./src/components/MyTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysSettings: typeof import('./src/views/components/SysSettings/index.vue')['default']
  }
}
